---@class Functions
---@field newNote fun(options: table<string, string>): function
---@field dailyNote fun(options: table<string, string>): function
---@field searchNotes fun(options: table<string, string>): function
