---@class Commands
---@field FfnotesNewNote fun(options: table<string, string>): function
---@field FfnotesDailyNote fun(options: table<string, string>): function
---@field FfnotesSearchNotes fun(options: table<string, string>): function
---@field FfnotesNewNoteFromTemplate fun(options: table<string, string>): function
